### ISSUE TITLE
not working when loading business bundle 

### ISSUE THREAD

**Issue by crazyone33** [varunon9/react-native-multiple-bundle#1]
with your step , **Pre-loading common.android.bundle** at MainActivity is OK! but, it is not working loading business bundle  immediately after Pre-loading common.android.bundle;

**Comment by varunkumar2** [comment]
Is it working after some delay e.g. post 300 ms?

**Comment by crazyone33** [comment]
> Is it working after some delay e.g. post 300 ms?

yeah，it is OK after delay some time, but how can we listen to the completion of the common bundle loading? add some delay time is risking.

**Comment by crazyone33** [comment]
> Is it working after some delay e.g. post 300 ms?

I found that if using react-native 0.63 or below is ok , it's not working after V0.64 ~ V0.67, do you have any ideas ?

**Comment by crazyone33** [comment]
```
mReactInstanceManager.addReactInstanceEventListener(new ReactInstanceManager.ReactInstanceEventListener() {
                  @Override
                   public void onReactContextInitialized(ReactContext context) {

                        // maybe common.bundle is loaded completely
                        // loadBusinessBundle();  // It's not working with React-Native version 0.64 ~ 0.67, have no idea why?
                }
           });
```

**Comment by crazyone33** [comment]
A thousand years later, I found the problem: ReactRootView does not reMeasure again after ReactNative 0.63, before adding to ViewGroup, it must calls startReactApplication() first.
